# Generated by Django 2.1 on 2018-08-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='midle_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
